# Generated by Django 4.2 on 2024-02-13 12:20

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [CreateExtension("pg_trgm")]

